select * from t1 division t2;
select * from t1 join t2, t3 inner join t4;
select * from t full join s on t.a=s.a;
select * from t1 join t2 using (c);
select * from t1 natural left outer join t;
select * from t natural right join s;
select * from t1 table1 right join t2 as table2;
SELECT * FROM s LEFT JOIN (q RIGHT JOIN sp ON q.sno=sp.sno) ON s.sno=q.sno;
select * from (t full join s) join u;
select c from (select a c from t) v where v.c=1;
select * from (t natural full join s) left join u on 10*s.c=u.b or 100*t.b=u.b;